<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class HotelSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('hotels')->truncate();
        Schema::enableForeignKeyConstraints();

        $hotels = [];

        // TOKYO (City ID: 1) - 35.6762, 139.6503
        $hotels[] = ['city_id' => 1, 'name' => 'Park Hyatt Tokyo', 'price_per_night' => 450.00, 'description' => 'Iconic luxury hotel featured in "Lost in Translation" with stunning skyline views. Features a 40th-floor pool, renowned New York Bar, and spacious rooms with floor-to-ceiling windows overlooking Mount Fuji.', 'localisation' => '35.6850, 139.6917', 'contact_number' => '+81-3-5322-1234', 'email' => 'reservations@hyatt.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 1, 'name' => 'The Peninsula Tokyo', 'price_per_night' => 520.00, 'description' => 'Elegant hotel near the Imperial Palace with world-class service. Features a stunning indoor pool, luxury spa, and complimentary Lexus transportation within the area.', 'localisation' => '35.6814, 139.7646', 'contact_number' => '+81-3-6270-2888', 'email' => 'peninsulatokyo@peninsula.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 1, 'name' => 'Capsule Hotel Anshin Oyado', 'price_per_night' => 60.00, 'description' => 'Modern capsule hotel with traditional onsen (hot spring) and sauna. Each pod includes TV, climate control, and complimentary breakfast for budget travelers.', 'localisation' => '35.6905, 139.7001', 'contact_number' => '+81-3-1234-5678', 'email' => 'info@anshin-oyado.jp', 'type' => 'budget', 'image' => 'https://images.pexels.com/photos/271618/pexels-photo-271618.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // KYOTO (City ID: 2) - 35.0116, 135.7681
        $hotels[] = ['city_id' => 2, 'name' => 'Hiiragiya Ryokan', 'price_per_night' => 380.00, 'description' => 'Historic 1818 ryokan offering authentic Japanese hospitality with tatami rooms and kaiseki dinners. Traditional gardens and private in-room hot spring baths provide a true cultural experience.', 'localisation' => '35.0105, 135.7621', 'contact_number' => '+81-75-221-5566', 'email' => 'reservations@hiiragiya.co.jp', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/261169/pexels-photo-261169.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 2, 'name' => 'The Ritz-Carlton Kyoto', 'price_per_night' => 650.00, 'description' => 'Ultra-luxury hotel along Kamogawa River with stunning Higashiyama mountain views. Features Michelin-starred dining, serene spa, and traditional Japanese garden.', 'localisation' => '35.0124, 135.7726', 'contact_number' => '+81-75-746-5555', 'email' => 'kyoto.reservations@ritzcarlton.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 2, 'name' => 'Kyoto Granbell Hotel', 'price_per_night' => 180.00, 'description' => 'Modern boutique hotel in historic Gion district near geisha houses. Rooftop terrace with city views and fusion restaurant serving innovative Japanese-Western cuisine.', 'localisation' => '35.0025, 135.7789', 'contact_number' => '+81-75-533-6111', 'email' => 'info@granbellhotel.com', 'type' => 'mid-range', 'image' => 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // OKINAWA (City ID: 3) - 26.3342, 127.8056
        $hotels[] = ['city_id' => 3, 'name' => 'Halekulani Okinawa', 'price_per_night' => 580.00, 'description' => 'Beachfront luxury resort with turquoise ocean views and tropical gardens. Multiple infinity pools, world-class spa, and award-winning seafood restaurants.', 'localisation' => '26.5342, 127.9056', 'contact_number' => '+81-98-123-4567', 'email' => 'reservations@halekulani.jp', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 3, 'name' => 'Hyatt Regency Seragaki Island', 'price_per_night' => 320.00, 'description' => 'Private island resort with multiple pools and private beach. Perfect for snorkeling, diving, and water sports with crystal-clear waters.', 'localisation' => '26.5123, 127.8876', 'contact_number' => '+81-98-960-4321', 'email' => 'okinawa.resort@hyatt.com', 'type' => 'resort', 'image' => 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 3, 'name' => 'The Busena Terrace', 'price_per_night' => 290.00, 'description' => 'Sprawling beach resort with golf course, tennis courts, and multiple pools. Features both hotel rooms and private villas with ocean or garden views.', 'localisation' => '26.5432, 127.8123', 'contact_number' => '+81-98-123-8888', 'email' => 'info@busena-terrace.jp', 'type' => 'resort', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // ROME (City ID: 4) - 41.9028, 12.4964
        $hotels[] = ['city_id' => 4, 'name' => 'Hotel Hassler Roma', 'price_per_night' => 580.00, 'description' => 'Iconic hotel atop Spanish Steps with panoramic views of Rome\'s historic center. Michelin-starred rooftop restaurant and elegantly decorated rooms with antique furnishings.', 'localisation' => '41.9059, 12.4817', 'contact_number' => '+39-06-699340', 'email' => 'info@hotelhassler.it', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 4, 'name' => 'The St. Regis Rome', 'price_per_night' => 490.00, 'description' => 'Historic 19th-century palace with Belle Époque architecture and crystal chandeliers. Signature butler service, lavish spa, and opulent Italian craftsmanship.', 'localisation' => '41.9025, 12.4958', 'contact_number' => '+39-06-47091', 'email' => 'rome.reservations@stregis.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 4, 'name' => 'Hotel Artemide', 'price_per_night' => 210.00, 'description' => 'Charming boutique hotel on Via Nazionale near Colosseum. Rooftop terrace with hot tub, wellness spa, and complimentary mini-bar with friendly service.', 'localisation' => '41.8986, 12.4956', 'contact_number' => '+39-06-489911', 'email' => 'reservations@hotelartemide.it', 'type' => 'mid-range', 'image' => 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // VENICE (City ID: 5) - 45.4408, 12.3155
        $hotels[] = ['city_id' => 5, 'name' => 'Belmond Hotel Cipriani', 'price_per_night' => 890.00, 'description' => 'Legendary hotel on Giudecca Island with stunning St. Mark\'s Square views. Accessible only by private boat with swimming pool, tennis courts, and lush gardens.', 'localisation' => '45.4314, 12.3400', 'contact_number' => '+39-041-240801', 'email' => 'cipriani@belmond.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 5, 'name' => 'The Gritti Palace', 'price_per_night' => 750.00, 'description' => 'Historic palace hotel on Grand Canal with restored 16th-century architecture. Luxury rooms with antique Venetian furnishings and canal views.', 'localisation' => '45.4332, 12.3320', 'contact_number' => '+39-041-794611', 'email' => 'reservations@grittipalace.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 5, 'name' => 'Hotel Danieli', 'price_per_night' => 520.00, 'description' => '14th-century palace hotel near Doges Palace with Gothic architecture. Rooftop terrace offering breathtaking lagoon and city views.', 'localisation' => '45.4345, 12.3405', 'contact_number' => '+39-041-5226480', 'email' => 'info@danielihotelvenice.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // AMALFI COAST (City ID: 6) - 40.6340, 14.6027
        $hotels[] = ['city_id' => 6, 'name' => 'Le Sirenuse', 'price_per_night' => 680.00, 'description' => 'Luxury hotel in Positano with breathtaking coastal views from every room. Michelin-starred restaurant, infinity pool, and elegant Mediterranean decor.', 'localisation' => '40.6285, 14.4828', 'contact_number' => '+39-089-875066', 'email' => 'info@sirenuse.it', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 6, 'name' => 'Hotel Santa Caterina', 'price_per_night' => 420.00, 'description' => 'Cliffside hotel with private beach access and stunning Amalfi Coast views. Saltwater pool, wellness center, and beautiful botanical gardens.', 'localisation' => '40.6345, 14.6028', 'contact_number' => '+39-089-871012', 'email' => 'info@hotelsantacaterina.it', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 6, 'name' => 'Villa Treville', 'price_per_night' => 950.00, 'description' => 'Exclusive villa hotel in Positano with private gardens and sea caves. Former home of legendary dancer Rudolf Nureyev with personalized butler service.', 'localisation' => '40.6270, 14.4850', 'contact_number' => '+39-089-812345', 'email' => 'info@villatreville.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // BANGKOK (City ID: 7) - 13.7367, 100.5231
        $hotels[] = ['city_id' => 7, 'name' => 'Mandarin Oriental Bangkok', 'price_per_night' => 450.00, 'description' => 'Iconic riverside hotel with legendary service since 1876. World-famous Author\'s Wing, Michelin-starred restaurants, and traditional Thai spa.', 'localisation' => '13.7389, 100.5125', 'contact_number' => '+66-2-6599000', 'email' => 'mobkk-reservations@mohg.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 7, 'name' => 'The Siam Hotel', 'price_per_night' => 380.00, 'description' => 'Art Deco luxury hotel with private pool villas along Chao Phraya River. Museum-quality antiques, Opium Spa, and personalized butler service.', 'localisation' => '13.7642, 100.4998', 'contact_number' => '+66-2-2066999', 'email' => 'reservations@thesiamhotel.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 7, 'name' => 'Lebua at State Tower', 'price_per_night' => 220.00, 'description' => 'Famous hotel with iconic Sky Bar rooftop featured in "Hangover 2". Spectacular 360-degree city views and award-winning restaurants.', 'localisation' => '13.7246, 100.5132', 'contact_number' => '+66-2-6249999', 'email' => 'reservations-bkk@lebua.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // CHIANG MAI (City ID: 8) - 18.7883, 98.9853
        $hotels[] = ['city_id' => 8, 'name' => 'Four Seasons Resort Chiang Mai', 'price_per_night' => 520.00, 'description' => 'Luxury resort surrounded by rice paddies and mountains. Traditional Lanna-style pavilions, organic farm, and renowned spa.', 'localisation' => '18.8270, 98.9510', 'contact_number' => '+66-53-298181', 'email' => 'reservations.cm@fourseasons.com', 'type' => 'resort', 'image' => 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 8, 'name' => '137 Pillars House', 'price_per_night' => 310.00, 'description' => 'Boutique hotel with colonial charm and private butlers. Historic teakwood house, lush gardens, and outdoor pool with rain shower.', 'localisation' => '18.7890, 99.0010', 'contact_number' => '+66-53-247788', 'email' => 'reservations@137pillarshouse.com', 'type' => 'boutique', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 8, 'name' => 'The Dhara Dhevi Chiang Mai', 'price_per_night' => 280.00, 'description' => 'Palatial resort modeled on ancient Lanna kingdom with traditional architecture. Private pool villas, cooking school, and cultural performances.', 'localisation' => '18.7850, 99.0050', 'contact_number' => '+66-53-888888', 'email' => 'info@dharadhevi.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // PHUKET (City ID: 9) - 7.8804, 98.3923
        $hotels[] = ['city_id' => 9, 'name' => 'Rosewood Phuket', 'price_per_night' => 550.00, 'description' => 'Beachfront luxury resort with stunning pool villas on Emerald Bay. Six restaurants, Asaya spa, and beachfront infinity pool.', 'localisation' => '7.8500, 98.3950', 'contact_number' => '+66-76-356888', 'email' => 'phuket@rosewoodhotels.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 9, 'name' => 'Keemala Phuket', 'price_per_night' => 390.00, 'description' => 'Unique resort with clay pool cottages and treehouses inspired by ancient Thai culture. Jungle setting with stunning Andaman Sea views.', 'localisation' => '7.8860, 98.2980', 'contact_number' => '+66-76-358777', 'email' => 'reservations@keemala.com', 'type' => 'boutique', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 9, 'name' => 'The Slate Phuket', 'price_per_night' => 210.00, 'description' => 'Designer resort with tin-mining heritage theme and avant-garde architecture. Multiple pools, art galleries, and award-winning restaurants.', 'localisation' => '7.8940, 98.2950', 'contact_number' => '+66-76-327006', 'email' => 'info@theslatephuket.com', 'type' => 'mid-range', 'image' => 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // PARIS (City ID: 10) - 48.8566, 2.3522
        $hotels[] = ['city_id' => 10, 'name' => 'Ritz Paris', 'price_per_night' => 980.00, 'description' => 'Legendary hotel in Place Vendôme with unmatched elegance since 1898. Coco Chanel\'s former residence, Hemingway Bar, and stunning garden.', 'localisation' => '48.8678, 2.3285', 'contact_number' => '+33-1-43163030', 'email' => 'reservations@ritzparis.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 10, 'name' => 'Four Seasons Hotel George V', 'price_per_night' => 1050.00, 'description' => 'Palatial hotel with stunning floral displays and three Michelin-starred restaurants. Marble courtyards, 24-karat gold accents, and exceptional service.', 'localisation' => '48.8695, 2.3016', 'contact_number' => '+33-1-49527000', 'email' => 'reservations.par@fourseasons.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 10, 'name' => 'Hotel Plaza Athénée', 'price_per_night' => 890.00, 'description' => 'Iconic hotel on Avenue Montaigne with Eiffel Tower views from private balconies. Dior spa, Alain Ducasse restaurant, and red geraniums.', 'localisation' => '48.8660, 2.3036', 'contact_number' => '+33-1-53676500', 'email' => 'reservations@plaza-athenee.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // FRENCH RIVIERA (City ID: 11) - 43.7102, 7.2620
        $hotels[] = ['city_id' => 11, 'name' => 'Hotel du Cap-Eden-Roc', 'price_per_night' => 1200.00, 'description' => 'Legendary hotel in Antibes with stunning Mediterranean views and saltwater pool carved into cliffs. Private lighthouse and 22-acre pine forest.', 'localisation' => '43.5533, 7.1289', 'contact_number' => '+33-4-93613901', 'email' => 'reservations@edencap.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 11, 'name' => 'Grand-Hôtel du Cap-Ferrat', 'price_per_night' => 890.00, 'description' => 'Belle Époque palace with Four Seasons service and stunning peninsula location. Three pools, spa, and Michelin-starred restaurant.', 'localisation' => '43.6858, 7.3303', 'contact_number' => '+33-4-93765050', 'email' => 'reservations.ferrat@fourseasons.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 11, 'name' => 'Hotel Negresco', 'price_per_night' => 480.00, 'description' => 'Historic hotel on Promenade des Anglais in Nice with listed monument status. Lavish Belle Époque decor, art collections, and revolving restaurant.', 'localisation' => '43.6948, 7.2612', 'contact_number' => '+33-4-93166400', 'email' => 'reservation@negresco.fr', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // BORDEAUX (City ID: 12) - 44.8378, -0.5792
        $hotels[] = ['city_id' => 12, 'name' => 'Les Sources de Caudalie', 'price_per_night' => 380.00, 'description' => 'Wine resort with spa and vineyard views in Pessac-Léognan. Vinotherapy treatments, Michelin-starred restaurant, and private lake.', 'localisation' => '44.7780, -0.5990', 'contact_number' => '+33-5-57654500', 'email' => 'info@lesourcesdecaudalie.com', 'type' => 'resort', 'image' => 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 12, 'name' => 'InterContinental Bordeaux Le Grand Hotel', 'price_per_night' => 290.00, 'description' => 'Grand hotel in heart of Bordeaux with rooftop pool overlooking Opera House. Elegant rooms, spa, and Michelin-starred Gordon Ramsay restaurant.', 'localisation' => '44.8419, -0.5736', 'contact_number' => '+33-5-57304400', 'email' => 'bordeaux@ihg.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 12, 'name' => 'Yndo Hotel', 'price_per_night' => 230.00, 'description' => 'Boutique hotel in restored 19th-century mansion with contemporary design. Secret garden, library lounge, and personalized service.', 'localisation' => '44.8385, -0.5768', 'contact_number' => '+33-5-56482828', 'email' => 'contact@yndohotel.com', 'type' => 'boutique', 'image' => 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // SYDNEY (City ID: 13) - -33.8688, 151.2093
        $hotels[] = ['city_id' => 13, 'name' => 'Park Hyatt Sydney', 'price_per_night' => 650.00, 'description' => 'Luxury hotel with direct views of Sydney Opera House and Harbour Bridge. Rooftop pool, spa, and waterfront dining at The Dining Room.', 'localisation' => '-33.8623, 151.2085', 'contact_number' => '+61-2-92561234', 'email' => 'sydney.park@hyatt.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 13, 'name' => 'Shangri-La Hotel Sydney', 'price_per_night' => 420.00, 'description' => 'Hotel with spectacular harbour views and altitude restaurant on 36th floor. Spa, indoor pool, and floor-to-ceiling windows in every room.', 'localisation' => '-33.8579, 151.2067', 'contact_number' => '+61-2-92506000', 'email' => 'slsy@shangri-la.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 13, 'name' => 'QT Sydney', 'price_per_night' => 280.00, 'description' => 'Designer hotel with quirky decor and vibrant atmosphere in historic Gowings and State Theatre buildings. Rooftop bar and spa.', 'localisation' => '-33.8700, 151.2080', 'contact_number' => '+61-2-82620000', 'email' => 'reservations@qtsydney.com.au', 'type' => 'boutique', 'image' => 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // GREAT BARRIER REEF (City ID: 14) - -18.2871, 147.6992
        $hotels[] = ['city_id' => 14, 'name' => 'Qualia Resort', 'price_per_night' => 780.00, 'description' => 'Ultra-luxury resort on Hamilton Island with private pavilions and infinity pools. Personalized golf buggies, spa, and stunning Whitsunday views.', 'localisation' => '-20.3505, 148.9550', 'contact_number' => '+61-7-49487800', 'email' => 'reservations@qualia.com.au', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 14, 'name' => 'Reef View Hotel', 'price_per_night' => 290.00, 'description' => 'Family-friendly hotel with spectacular ocean views on Hamilton Island. Large pool, multiple restaurants, and easy reef access.', 'localisation' => '-20.3510, 148.9560', 'contact_number' => '+61-7-49469999', 'email' => 'reefview@hamiltonisland.com.au', 'type' => 'mid-range', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 14, 'name' => 'Lizard Island Resort', 'price_per_night' => 1100.00, 'description' => 'Exclusive resort on private island with direct reef access and 24 pristine beaches. Only 40 rooms, gourmet dining, and marine biology center.', 'localisation' => '-14.6680, 145.4560', 'contact_number' => '+61-7-40606001', 'email' => 'reservations@lizardisland.com.au', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // MELBOURNE (City ID: 15) - -37.8136, 144.9631
        $hotels[] = ['city_id' => 15, 'name' => 'Crown Towers Melbourne', 'price_per_night' => 450.00, 'description' => 'Luxury hotel with casino, spa, and fine dining on Southbank. Award-winning restaurants, designer shopping, and spectacular city views.', 'localisation' => '-37.8220, 144.9590', 'contact_number' => '+61-3-92928888', 'email' => 'crown.towers@crownmelbourne.com.au', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 15, 'name' => 'The Langham Melbourne', 'price_per_night' => 350.00, 'description' => 'Elegant hotel on Southbank with Yarra River views and signature pink champagne afternoon tea. Spa, pool, and Chuan wellness treatments.', 'localisation' => '-37.8190, 144.9600', 'contact_number' => '+61-3-86968888', 'email' => 'melbourne@langhamhotels.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 15, 'name' => 'Adelphi Hotel', 'price_per_night' => 220.00, 'description' => 'Boutique hotel famous for its honeycomb pool suspended over Flinders Lane. Retro design, street art location, and quirky decor.', 'localisation' => '-37.8170, 144.9660', 'contact_number' => '+61-3-80800088', 'email' => 'stay@adelphihotel.com.au', 'type' => 'boutique', 'image' => 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // RIO DE JANEIRO (City ID: 16) - -22.9068, -43.1729
        $hotels[] = ['city_id' => 16, 'name' => 'Belmond Copacabana Palace', 'price_per_night' => 580.00, 'description' => 'Iconic Art Deco hotel on Copacabana Beach since 1923. Pool shaped like a ship, spa, and Michelin-starred restaurant Mee.', 'localisation' => '-22.9670, -43.1830', 'contact_number' => '+55-21-25487070', 'email' => 'reservations@copacabanapalace.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 16, 'name' => 'Fasano Rio de Janeiro', 'price_per_night' => 420.00, 'description' => 'Sleek luxury hotel on Ipanema Beach with retro 1950s design. Rooftop pool, Philippe Starck furniture, and top Italian restaurant.', 'localisation' => '-22.9840, -43.2040', 'contact_number' => '+55-21-32024000', 'email' => 'fasano@fasano.com.br', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 16, 'name' => 'Hotel Nacional Rio', 'price_per_night' => 190.00, 'description' => 'Historic hotel with stunning coastline views, recently restored to its 1970s modernist glory. Iconic architecture and beautiful pool.', 'localisation' => '-23.0010, -43.2930', 'contact_number' => '+55-21-35009100', 'email' => 'reservas@hotelnacional.com.br', 'type' => 'mid-range', 'image' => 'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // AMAZON RAINFOREST (City ID: 17) - -3.4653, -62.2159
        $hotels[] = ['city_id' => 17, 'name' => 'Anavilhanas Jungle Lodge', 'price_per_night' => 320.00, 'description' => 'Eco-lodge in heart of Amazon with jungle tours and floating boardwalks. Solar-powered, local guide excursions, and wildlife spotting.', 'localisation' => '-2.6370, -60.9570', 'contact_number' => '+55-92-32334285', 'email' => 'reservas@anavilhanas.com.br', 'type' => 'boutique', 'image' => 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 17, 'name' => 'Juma Amazon Lodge', 'price_per_night' => 280.00, 'description' => 'Remote lodge offering authentic Amazon experiences with all-inclusive packages. Canopy tower, caiman spotting, and indigenous culture tours.', 'localisation' => '-3.0340, -60.4210', 'contact_number' => '+55-92-991145955', 'email' => 'contato@jumaamazonlodge.com.br', 'type' => 'economy', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 17, 'name' => 'Aria Amazon Cruises', 'price_per_night' => 750.00, 'description' => 'Luxury river cruise exploring Amazon with private suites and panoramic windows. Expert naturalists, skiff excursions, and gourmet dining.', 'localisation' => '-3.1300, -58.4300', 'contact_number' => '+51-1-6191900', 'email' => 'reservations@ariaamazon.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // SALVADOR (City ID: 18) - -12.9714, -38.5014
        $hotels[] = ['city_id' => 18, 'name' => 'Fera Palace Hotel', 'price_per_night' => 210.00, 'description' => 'Art Deco boutique hotel in historic center with rooftop pool and bay views. Original 1930s architecture with modern luxury amenities.', 'localisation' => '-12.9740, -38.5120', 'contact_number' => '+55-71-32028100', 'email' => 'reservas@ferapalacehotel.com', 'type' => 'boutique', 'image' => 'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 18, 'name' => 'Hotel Casa do Amarelindo', 'price_per_night' => 160.00, 'description' => 'Charming hotel with panoramic bay views in Pelourinho district. Colonial architecture, organic breakfast, and relaxing terrace.', 'localisation' => '-12.9720, -38.5090', 'contact_number' => '+55-71-32664400', 'email' => 'reservas@casadamarelindo.com', 'type' => 'mid-range', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 18, 'name' => 'Zank by Toque Hotel', 'price_per_night' => 190.00, 'description' => 'Contemporary boutique hotel with pool and modern design in Rio Vermelho. Art gallery, fusion restaurant, and vibrant atmosphere.', 'localisation' => '-13.0000, -38.5000', 'contact_number' => '+55-71-33360700', 'email' => 'reservas@zankhotel.com.br', 'type' => 'boutique', 'image' => 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // JAIPUR (City ID: 19) - 26.9124, 75.7873
        $hotels[] = ['city_id' => 19, 'name' => 'Rambagh Palace', 'price_per_night' => 480.00, 'description' => 'Former royal palace transformed into luxury hotel with stunning Mughal gardens. Polo bar, royal butlers, and peacock-filled courtyards.', 'localisation' => '26.9010, 75.8140', 'contact_number' => '+91-141-2211919', 'email' => 'reservations.rambagh@tajhotels.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 19, 'name' => 'The Oberoi Rajvilas', 'price_per_night' => 420.00, 'description' => 'Luxury resort with beautiful gardens, spa, and traditional haveli architecture. Private pool villas and award-winning Indian cuisine.', 'localisation' => '26.8710, 75.7770', 'contact_number' => '+91-141-2680101', 'email' => 'reservations@oberoirajvilas.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 19, 'name' => 'Jai Mahal Palace', 'price_per_night' => 280.00, 'description' => '18th-century palace with 18 acres of Mughal gardens and ancient banyan tree. Heritage rooms, spa, and cultural performances.', 'localisation' => '26.8880, 75.8050', 'contact_number' => '+91-141-2223636', 'email' => 'reservations.jaimahalpalace@tajhotels.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // GOA (City ID: 20) - 15.2993, 74.1240
        $hotels[] = ['city_id' => 20, 'name' => 'W Goa', 'price_per_night' => 350.00, 'description' => 'Trendy beachfront resort with vibrant nightlife and modern design. WET pool deck, WooBar, and AWAY spa with local treatments.', 'localisation' => '15.4700, 73.8000', 'contact_number' => '+91-832-6713333', 'email' => 'reservations@wgoa.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 20, 'name' => 'Taj Fort Aguada Resort', 'price_per_night' => 320.00, 'description' => 'Heritage resort with private beach and 16th-century Portuguese fort. Multiple pools, spa, and stunning Arabian Sea views.', 'localisation' => '15.4940, 73.7710', 'contact_number' => '+91-832-6645858', 'email' => 'reservations.fortaguada@tajhotels.com', 'type' => 'resort', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 20, 'name' => 'Alila Diwa Goa', 'price_per_night' => 240.00, 'description' => 'Modern resort with infinity pool and rice paddy views in South Goa. Contemporary design, spa, and beach shuttle service.', 'localisation' => '15.2780, 73.9220', 'contact_number' => '+91-832-2702700', 'email' => 'goa@alilahotels.com', 'type' => 'resort', 'image' => 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // MANALI (City ID: 21) - 32.2432, 77.1889
        $hotels[] = ['city_id' => 21, 'name' => 'The Himalayan', 'price_per_night' => 180.00, 'description' => 'Luxury resort with stunning mountain views and traditional Himachali architecture. Spa, multi-cuisine restaurant, and adventure activities.', 'localisation' => '32.2550, 77.1890', 'contact_number' => '+91-1902-252727', 'email' => 'info@thehimalayan.com', 'type' => 'mid-range', 'image' => 'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 21, 'name' => 'Solang Valley Resort', 'price_per_night' => 140.00, 'description' => 'Adventure resort near skiing slopes with panoramic mountain views. Bonfires, indoor games, and guided trekking excursions.', 'localisation' => '32.3130, 77.1550', 'contact_number' => '+91-98160-12345', 'email' => 'resort@solangvalley.com', 'type' => 'economy', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 21, 'name' => 'Apple Country Resort', 'price_per_night' => 110.00, 'description' => 'Cozy resort surrounded by apple orchards with mountain views. Family-friendly, bonfire evenings, and organic Himachali cuisine.', 'localisation' => '32.2320, 77.2000', 'contact_number' => '+91-1902-250123', 'email' => 'stay@applecountryresort.com', 'type' => 'budget', 'image' => 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // BANFF (City ID: 22) - 51.1784, -115.5708
        $hotels[] = ['city_id' => 22, 'name' => 'Fairmont Banff Springs', 'price_per_night' => 550.00, 'description' => 'Iconic "Castle in the Rockies" with stunning mountain and river views. Golf course, spa, and world-class dining.', 'localisation' => '51.1650, -115.5620', 'contact_number' => '+1-403-7622211', 'email' => 'banffsprings@fairmont.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 22, 'name' => 'Rimrock Resort Hotel', 'price_per_night' => 380.00, 'description' => 'Cliffside luxury hotel overlooking Banff National Park. Award-winning spa, panoramic views, and fine dining.', 'localisation' => '51.1700, -115.5700', 'contact_number' => '+1-403-7623356', 'email' => 'reservations@rimrockresort.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 22, 'name' => 'Banff Caribou Lodge', 'price_per_night' => 180.00, 'description' => 'Cozy mountain lodge with rooftop hot springs and fireplace lounge. Rustic decor, free breakfast, and ski storage.', 'localisation' => '51.1750, -115.5750', 'contact_number' => '+1-403-7625887', 'email' => 'info@banffcariboulodge.com', 'type' => 'mid-range', 'image' => 'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // VANCOUVER (City ID: 23) - 49.2827, -123.1207
        $hotels[] = ['city_id' => 23, 'name' => 'Fairmont Pacific Rim', 'price_per_night' => 480.00, 'description' => 'Luxury waterfront hotel with stunning harbor and mountain views. Rooftop pool, Willow Stream spa, and award-winning cocktails.', 'localisation' => '49.2880, -123.1170', 'contact_number' => '+1-604-6955300', 'email' => 'pacificrim@fairmont.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 23, 'name' => 'Rosewood Hotel Georgia', 'price_per_night' => 420.00, 'description' => 'Historic hotel restored to its 1920s glory with modern luxury. Sense spa, live jazz lounge, and elegant rooms.', 'localisation' => '49.2830, -123.1190', 'contact_number' => '+1-604-6825566', 'email' => 'reservations.hotelgeorgia@rosewoodhotels.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 23, 'name' => 'The Burrard', 'price_per_night' => 180.00, 'description' => 'Retro boutique hotel with courtyard garden and free bikes. Mid-century modern design, free parking, and central location.', 'localisation' => '49.2830, -123.1210', 'contact_number' => '+1-604-6812334', 'email' => 'hello@theburrard.com', 'type' => 'boutique', 'image' => 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // QUEBEC CITY (City ID: 24) - 46.8139, -71.2080
        $hotels[] = ['city_id' => 24, 'name' => 'Fairmont Le Château Frontenac', 'price_per_night' => 520.00, 'description' => 'Iconic castle hotel overlooking St. Lawrence River, most photographed in the world. History tours, fine dining, and elegant rooms.', 'localisation' => '46.8120, -71.2050', 'contact_number' => '+1-418-6923861', 'email' => 'chateaufrontenac@fairmont.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 24, 'name' => 'Auberge Saint-Antoine', 'price_per_night' => 350.00, 'description' => 'Relais & Châteaux hotel built on historic ruins with museum-quality artifacts. Waterfront location and exceptional service.', 'localisation' => '46.8130, -71.2000', 'contact_number' => '+1-418-6922211', 'email' => 'info@aubergesaintantoine.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 24, 'name' => 'Hôtel Le Germain Québec', 'price_per_night' => 220.00, 'description' => 'Contemporary boutique hotel in Old Quebec with modern design. Rooftop terrace, local art, and complimentary wine tasting.', 'localisation' => '46.8140, -71.2080', 'contact_number' => '+1-418-6922224', 'email' => 'quebec@germainhotels.com', 'type' => 'boutique', 'image' => 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // MARRAKECH (City ID: 25) - 31.6295, -7.9811
        $hotels[] = ['city_id' => 25, 'name' => 'La Mamounia', 'price_per_night' => 680.00, 'description' => 'Legendary palace hotel with stunning Moorish architecture and gardens. Multiple pools, spa, and Michelin-starred dining.', 'localisation' => '31.6250, -7.9900', 'contact_number' => '+212-524-388600', 'email' => 'reservations@mamounia.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 25, 'name' => 'Royal Mansour Marrakech', 'price_per_night' => 850.00, 'description' => 'Luxury riads with private rooftop pools and butler service. Three-Michelin-star restaurant, spa, and intricate craftsmanship.', 'localisation' => '31.6300, -7.9900', 'contact_number' => '+212-524-380800', 'email' => 'info@royalmansour.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 25, 'name' => 'Riad Yasmine', 'price_per_night' => 120.00, 'description' => 'Instagram-famous riad with iconic green plunge pool and traditional Moroccan decor. Rooftop terrace, mint tea, and intimate atmosphere.', 'localisation' => '31.6280, -7.9850', 'contact_number' => '+212-524-382949', 'email' => 'contact@riadyasmine.com', 'type' => 'boutique', 'image' => 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // SAHARA (City ID: 26) - 27.1318, 12.0528
        $hotels[] = ['city_id' => 26, 'name' => 'Merzouga Luxury Desert Camp', 'price_per_night' => 280.00, 'description' => 'Luxury desert camp with private tents featuring en-suite bathrooms and comfortable bedding. Camel treks, sandboarding, traditional Berber music, and stargazing in the Sahara.', 'localisation' => '31.1000, -4.0000', 'contact_number' => '+212-661-123456', 'email' => 'info@merzougaluxurycamp.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 26, 'name' => 'Erg Chebbi Desert Lodge', 'price_per_night' => 150.00, 'description' => 'Eco-friendly desert lodge at the edge of Erg Chebbi dunes with stunning sunrise views. Traditional meals, camel rides, and comfortable Berber tents.', 'localisation' => '31.1500, -3.9500', 'contact_number' => '+212-662-789012', 'email' => 'contact@ergchebbilodge.com', 'type' => 'mid-range', 'image' => 'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 26, 'name' => 'Desert Heart Camp', 'price_per_night' => 80.00, 'description' => 'Budget-friendly desert camp offering authentic Bedouin experience. Simple tents, communal meals, bonfire evenings, and camel trekking included.', 'localisation' => '31.0800, -4.0200', 'contact_number' => '+212-668-345678', 'email' => 'stay@desertheart.com', 'type' => 'budget', 'image' => 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // CHEFCHAOUEN (City ID: 27) - 35.1686, -5.2697
        $hotels[] = ['city_id' => 27, 'name' => 'Lina Ryad & Spa', 'price_per_night' => 180.00, 'description' => 'Beautiful riad in the heart of the blue city with rooftop terrace and stunning mountain views. Traditional Moroccan decor, spa, and delicious breakfast.', 'localisation' => '35.1680, -5.2630', 'contact_number' => '+212-539-988888', 'email' => 'info@linaryad.com', 'type' => 'boutique', 'image' => 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 27, 'name' => 'Dar Echchaouen', 'price_per_night' => 120.00, 'description' => 'Charming traditional house with blue-washed walls and panoramic terrace. Cozy rooms, warm hospitality, and authentic Moroccan breakfast.', 'localisation' => '35.1700, -5.2640', 'contact_number' => '+212-539-989999', 'email' => 'reservations@darechchaouen.com', 'type' => 'mid-range', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 27, 'name' => 'Hotel Parador', 'price_per_night' => 70.00, 'description' => 'Budget hotel in central Chefchaouen with basic amenities and friendly service. Walking distance to main square and blue streets.', 'localisation' => '35.1670, -5.2620', 'contact_number' => '+212-539-987654', 'email' => 'contact@hotelparador.com', 'type' => 'economy', 'image' => 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // BARCELONA (City ID: 28) - 41.3851, 2.1734
        $hotels[] = ['city_id' => 28, 'name' => 'Hotel Arts Barcelona', 'price_per_night' => 490.00, 'description' => 'Iconic luxury hotel with stunning Mediterranean views and two Michelin-starred Enoteca restaurant. Rooftop pool, art collection, and beach access.', 'localisation' => '41.3860, 2.1970', 'contact_number' => '+34-93-2211000', 'email' => 'reservations@hotelartsbarcelona.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 28, 'name' => 'Majestic Hotel & Spa', 'price_per_night' => 350.00, 'description' => 'Belle Époque luxury hotel on Passeig de Gràcia with rooftop terrace and city views. Elegant rooms, spa, and gourmet dining.', 'localisation' => '41.3920, 2.1640', 'contact_number' => '+34-93-4881717', 'email' => 'info@majestichotel.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 28, 'name' => 'Generator Barcelona', 'price_per_night' => 45.00, 'description' => 'Trendy hostel with private rooms and dorms near Sagrada Familia. Rooftop bar, pool, and social atmosphere for budget travelers.', 'localisation' => '41.4060, 2.1740', 'contact_number' => '+34-93-1234567', 'email' => 'barcelona@generatorhostels.com', 'type' => 'budget', 'image' => 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // IBIZA (City ID: 29) - 38.9064, 1.4201
        $hotels[] = ['city_id' => 29, 'name' => 'Ushuaïa Ibiza Beach Hotel', 'price_per_night' => 450.00, 'description' => 'Famous party hotel with outdoor stage and nightly DJ performances. Beachfront location, multiple pools, and vibrant nightlife.', 'localisation' => '38.8960, 1.3930', 'contact_number' => '+34-971-396000', 'email' => 'info@ushuaiaibiza.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 29, 'name' => 'Nobu Hotel Ibiza Bay', 'price_per_night' => 520.00, 'description' => 'Chic beachfront resort with Nobu restaurant and world-class spa. Stylish rooms, family-friendly, and stunning sunset views.', 'localisation' => '38.9100, 1.4350', 'contact_number' => '+34-971-198000', 'email' => 'reservations@nobuhotelibiza.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 29, 'name' => 'Hostal La Torre', 'price_per_night' => 120.00, 'description' => 'Bohemian boutique hotel with stunning sunset views over the Mediterranean. Rustic charm, vegetarian restaurant, and relaxing atmosphere.', 'localisation' => '38.9200, 1.4400', 'contact_number' => '+34-971-197011', 'email' => 'info@hostal-latorre.com', 'type' => 'boutique', 'image' => 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // SEVILLE (City ID: 30) - 37.3891, -5.9845
        $hotels[] = ['city_id' => 30, 'name' => 'Hotel Alfonso XIII', 'price_per_night' => 420.00, 'description' => 'Historic luxury hotel built for 1929 exhibition with stunning Mudéjar architecture. Pool, spa, and Andalusian courtyard.', 'localisation' => '37.3800, -5.9900', 'contact_number' => '+34-95-4917000', 'email' => 'alfonsoxiii@luxurycollection.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 30, 'name' => 'EME Catedral Hotel', 'price_per_night' => 220.00, 'description' => 'Modern boutique hotel with rooftop pool and spectacular cathedral views. Central location, fusion restaurant, and stylish decor.', 'localisation' => '37.3860, -5.9940', 'contact_number' => '+34-95-4504010', 'email' => 'reservas@emehotel.com', 'type' => 'boutique', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 30, 'name' => 'Hotel Simon', 'price_per_night' => 85.00, 'description' => 'Budget-friendly hotel in former 18th-century mansion near the cathedral. Simple rooms, charming courtyard, and central location.', 'localisation' => '37.3880, -5.9910', 'contact_number' => '+34-95-4226660', 'email' => 'info@hotelsimonsevilla.com', 'type' => 'economy', 'image' => 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // SANTORINI (City ID: 31) - 36.3932, 25.4615
        $hotels[] = ['city_id' => 31, 'name' => 'Katikies Hotel', 'price_per_night' => 650.00, 'description' => 'Iconic cliffside hotel with stunning caldera views and infinity pools. White-washed architecture, fine dining, and sunset views.', 'localisation' => '36.4300, 25.4260', 'contact_number' => '+30-22860-71401', 'email' => 'reservations@katikies.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 31, 'name' => 'Canaves Oia Suites', 'price_per_night' => 580.00, 'description' => 'Luxury suites carved into cliffside with private plunge pools and caldera views. Cave-style rooms and exceptional service.', 'localisation' => '36.4620, 25.3780', 'contact_number' => '+30-22860-71685', 'email' => 'info@canaves.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 31, 'name' => 'Dream Island Hotel', 'price_per_night' => 110.00, 'description' => 'Affordable hotel in Fira with traditional Cycladic architecture and pool. Simple rooms, friendly service, and easy access to attractions.', 'localisation' => '36.4200, 25.4320', 'contact_number' => '+30-22860-23456', 'email' => 'info@dreamisland.gr', 'type' => 'economy', 'image' => 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // ATHENS (City ID: 32) - 37.9838, 23.7275
        $hotels[] = ['city_id' => 32, 'name' => 'Hotel Grande Bretagne', 'price_per_night' => 480.00, 'description' => 'Legendary luxury hotel with stunning Acropolis views and rooftop pool. Historic landmark, spa, and Michelin-starred dining.', 'localisation' => '37.9780, 23.7370', 'contact_number' => '+30-210-3330000', 'email' => 'reservations.gb@luxurycollection.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 32, 'name' => 'Electra Metropolis', 'price_per_night' => 210.00, 'description' => 'Modern hotel with rooftop pool and breathtaking Acropolis views. Central location, spa, and contemporary design.', 'localisation' => '37.9760, 23.7310', 'contact_number' => '+30-210-1234567', 'email' => 'info@electrametropolis.gr', 'type' => 'mid-range', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 32, 'name' => 'Athens Backpackers', 'price_per_night' => 35.00, 'description' => 'Popular hostel with rooftop terrace and Acropolis view. Dorms and private rooms, bar, and social atmosphere.', 'localisation' => '37.9700, 23.7280', 'contact_number' => '+30-210-1234568', 'email' => 'info@athensbackpackers.com', 'type' => 'budget', 'image' => 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // CRETE (City ID: 33) - 35.2401, 24.8093
        $hotels[] = ['city_id' => 33, 'name' => 'Blue Palace Resort', 'price_per_night' => 450.00, 'description' => 'Luxury resort with private beach and stunning views of Spinalonga island. Multiple pools, spa, and gourmet restaurants.', 'localisation' => '35.2850, 25.7000', 'contact_number' => '+30-28410-65600', 'email' => 'reservations@bluepalace.gr', 'type' => 'resort', 'image' => 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 33, 'name' => 'Domes of Elounda', 'price_per_night' => 380.00, 'description' => 'Design resort with private pools and stunning sea views. Adults-only, spa, and exquisite Mediterranean cuisine.', 'localisation' => '35.2700, 25.7200', 'contact_number' => '+30-28410-41200', 'email' => 'info@domesofelounda.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 33, 'name' => 'Cretan Villa Hotel', 'price_per_night' => 90.00, 'description' => 'Family-run hotel with traditional Cretan hospitality and garden. Simple rooms, home-cooked meals, and peaceful atmosphere.', 'localisation' => '35.3300, 25.1000', 'contact_number' => '+30-2810-123456', 'email' => 'info@cretanvilla.gr', 'type' => 'economy', 'image' => 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // QUEENSTOWN (City ID: 34) - -45.0312, 168.6626
        $hotels[] = ['city_id' => 34, 'name' => 'Eichardt\'s Private Hotel', 'price_per_night' => 650.00, 'description' => 'Luxury boutique hotel with stunning lake and mountain views. Historic building, fireplace suites, and exceptional service.', 'localisation' => '-45.0310, 168.6620', 'contact_number' => '+64-3-4410450', 'email' => 'reservations@eichardts.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 34, 'name' => 'Matakauri Lodge', 'price_per_night' => 720.00, 'description' => 'Ultra-luxury lodge with breathtaking views of The Remarkables mountains. Spa, fine dining, and personalized service.', 'localisation' => '-45.0500, 168.6500', 'contact_number' => '+64-3-4411008', 'email' => 'stay@matakauri.co.nz', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 34, 'name' => 'Nomads Queenstown', 'price_per_night' => 40.00, 'description' => 'Adventure hostel with social atmosphere and ski storage. Dorms, private rooms, free WiFi, and activity booking.', 'localisation' => '-45.0315, 168.6610', 'contact_number' => '+64-3-4411234', 'email' => 'queenstown@nomadshostels.com', 'type' => 'budget', 'image' => 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // ROTORUA (City ID: 35) - -38.1368, 176.2497
        $hotels[] = ['city_id' => 35, 'name' => 'Polynesian Spa Lodge', 'price_per_night' => 320.00, 'description' => 'Luxury lodge with private access to famous geothermal hot springs. Spa treatments, lake views, and healing mineral waters.', 'localisation' => '-38.1300, 176.2500', 'contact_number' => '+64-7-3481329', 'email' => 'info@polynesianspa.co.nz', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 35, 'name' => 'Treetops Lodge', 'price_per_night' => 280.00, 'description' => 'Eco-lodge in ancient forest with geothermal hot pools and wildlife. Adventure activities, fine dining, and nature experiences.', 'localisation' => '-38.2000, 176.2000', 'contact_number' => '+64-7-3332060', 'email' => 'reservations@treetops.co.nz', 'type' => 'boutique', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 35, 'name' => 'Rotorua Central Backpackers', 'price_per_night' => 35.00, 'description' => 'Budget hostel with geothermal pool and social atmosphere. Dorms, kitchen facilities, and activity desk.', 'localisation' => '-38.1380, 176.2500', 'contact_number' => '+64-7-1234567', 'email' => 'stay@rotoruacentral.com', 'type' => 'budget', 'image' => 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // AUCKLAND (City ID: 36) - -36.8485, 174.7633
        $hotels[] = ['city_id' => 36, 'name' => 'Park Hyatt Auckland', 'price_per_night' => 480.00, 'description' => 'Luxury waterfront hotel with stunning harbor views and rooftop bar. Spa, infinity pool, and fine dining restaurants.', 'localisation' => '-36.8430, 174.7650', 'contact_number' => '+64-9-3661234', 'email' => 'auckland@hyatt.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 36, 'name' => 'The Hotel Britomart', 'price_per_night' => 320.00, 'description' => 'Heritage boutique hotel in revitalized Britomart district. Designer rooms, local art, and sustainable practices.', 'localisation' => '-36.8440, 174.7700', 'contact_number' => '+64-9-1234567', 'email' => 'stay@hotelbritomart.com', 'type' => 'boutique', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 36, 'name' => 'Kiwi International Hotel', 'price_per_night' => 65.00, 'description' => 'Budget hotel in central Auckland with basic rooms and shared facilities. Close to public transport and attractions.', 'localisation' => '-36.8500, 174.7600', 'contact_number' => '+64-9-1234568', 'email' => 'info@kiwihotel.co.nz', 'type' => 'economy', 'image' => 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // CAIRO (City ID: 37) - 30.0444, 31.2357
        $hotels[] = ['city_id' => 37, 'name' => 'Marriott Mena House Cairo', 'price_per_night' => 350.00, 'description' => 'Historic hotel at the foot of the Great Pyramids with stunning views. Royal gardens, spa, and fine dining.', 'localisation' => '29.9870, 31.1350', 'contact_number' => '+20-2-33773222', 'email' => 'reservations.menahouse@marriott.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 37, 'name' => 'Four Seasons Cairo', 'price_per_night' => 420.00, 'description' => 'Luxury Nile-front hotel with spectacular river and city views. Multiple pools, spa, and award-winning restaurants.', 'localisation' => '30.0580, 31.2230', 'contact_number' => '+20-2-27917000', 'email' => 'reservations.cairo@fourseasons.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 37, 'name' => 'Cairo Downtown Hostel', 'price_per_night' => 25.00, 'description' => 'Budget hostel in central Cairo with rooftop terrace and city views. Basic dorms, free breakfast, and friendly staff.', 'localisation' => '30.0440, 31.2360', 'contact_number' => '+20-2-1234567', 'email' => 'info@cairohostel.com', 'type' => 'budget', 'image' => 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // HURGHADA (City ID: 38) - 27.2579, 33.8116
        $hotels[] = ['city_id' => 38, 'name' => 'Steigenberger Aqua Magic', 'price_per_night' => 180.00, 'description' => 'Family-friendly resort with water slides and multiple pools. Private beach, diving center, and all-inclusive options.', 'localisation' => '27.2500, 33.8100', 'contact_number' => '+20-65-3467777', 'email' => 'info@aquamagic.com', 'type' => 'resort', 'image' => 'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 38, 'name' => 'Jaz Aquamarine Resort', 'price_per_night' => 210.00, 'description' => 'Luxury resort with private beach and stunning Red Sea views. Multiple pools, spa, and water sports.', 'localisation' => '27.2600, 33.8200', 'contact_number' => '+20-65-3469999', 'email' => 'reservations@jazaquamarine.com', 'type' => 'resort', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 38, 'name' => 'Seaview Budget Hotel', 'price_per_night' => 45.00, 'description' => 'Simple budget hotel walking distance to beach and marina. Basic rooms, free WiFi, and economical rates.', 'localisation' => '27.2550, 33.8150', 'contact_number' => '+20-65-1234567', 'email' => 'stay@seaviewhurghada.com', 'type' => 'budget', 'image' => 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // LUXOR (City ID: 39) - 25.6872, 32.6396
        $hotels[] = ['city_id' => 39, 'name' => 'Al Moudira Hotel', 'price_per_night' => 220.00, 'description' => 'Beautiful palace-style hotel with traditional architecture and gardens. Large pool, spa, and authentic Egyptian decor.', 'localisation' => '25.6800, 32.6400', 'contact_number' => '+20-95-2280000', 'email' => 'info@almoudira.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 39, 'name' => 'Hilton Luxor Resort', 'price_per_night' => 160.00, 'description' => 'Nile-front resort with stunning views of the West Bank and mountains. Pool, spa, and multiple restaurants.', 'localisation' => '25.6900, 32.6300', 'contact_number' => '+20-95-2374444', 'email' => 'reservations.luxor@hilton.com', 'type' => 'mid-range', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 39, 'name' => 'Happy Land Hotel', 'price_per_night' => 35.00, 'description' => 'Budget hotel near Luxor Temple with simple rooms and friendly service. Rooftop terrace with Nile views.', 'localisation' => '25.6850, 32.6450', 'contact_number' => '+20-95-1234567', 'email' => 'info@happyluxor.com', 'type' => 'budget', 'image' => 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // CANCUN (City ID: 40) - 21.1619, -86.8515
        $hotels[] = ['city_id' => 40, 'name' => 'Le Blanc Spa Resort', 'price_per_night' => 650.00, 'description' => 'Adults-only luxury all-inclusive resort with white-glove service. Infinity pools, world-class spa, and gourmet dining.', 'localisation' => '21.1500, -86.7800', 'contact_number' => '+52-998-8817340', 'email' => 'reservations@leblancsparesort.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 40, 'name' => 'Nizuc Resort & Spa', 'price_per_night' => 580.00, 'description' => 'Luxury resort on Punta Nizuc with stunning ocean views and private beaches. Multiple pools, spa, and fine dining.', 'localisation' => '21.0300, -86.7800', 'contact_number' => '+52-998-8915800', 'email' => 'info@nizuc.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 40, 'name' => 'Mayan Monkey Hostel', 'price_per_night' => 25.00, 'description' => 'Social hostel with pool, bar, and rooftop terrace near the beach. Dorms, private rooms, and party atmosphere.', 'localisation' => '21.1600, -86.8500', 'contact_number' => '+52-998-1234567', 'email' => 'info@mayanmonkey.com', 'type' => 'budget', 'image' => 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // MEXICO CITY (City ID: 41) - 19.4326, -99.1332
        $hotels[] = ['city_id' => 41, 'name' => 'Four Seasons Mexico City', 'price_per_night' => 490.00, 'description' => 'Luxury hotel with beautiful courtyard garden and central location. Spa, pool, and award-winning restaurants.', 'localisation' => '19.4250, -99.1600', 'contact_number' => '+52-55-52301800', 'email' => 'reservations.mex@fourseasons.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 41, 'name' => 'Gran Hotel Ciudad de México', 'price_per_night' => 150.00, 'description' => 'Historic Art Nouveau hotel with stunning stained glass ceiling overlooking Zócalo. Elegant rooms and central location.', 'localisation' => '19.4320, -99.1330', 'contact_number' => '+52-55-10838800', 'email' => 'reservations@granhotelcdmx.com', 'type' => 'mid-range', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 41, 'name' => 'Hostel Amigo', 'price_per_night' => 20.00, 'description' => 'Budget hostel in historic center with rooftop terrace and free breakfast. Dorms, private rooms, and social atmosphere.', 'localisation' => '19.4350, -99.1350', 'contact_number' => '+52-55-12345678', 'email' => 'info@hostelamigo.com', 'type' => 'budget', 'image' => 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // CHICHEN ITZA (City ID: 42) - 20.6843, -88.5678
        $hotels[] = ['city_id' => 42, 'name' => 'Mayaland Hotel', 'price_per_night' => 180.00, 'description' => 'Historic hotel located inside Chichen Itza archaeological park with private access to ruins. Pool, restaurant, and gardens.', 'localisation' => '20.6820, -88.5700', 'contact_number' => '+52-985-8510100', 'email' => 'info@mayaland.com', 'type' => 'mid-range', 'image' => 'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 42, 'name' => 'Hacienda Chichen Resort', 'price_per_night' => 140.00, 'description' => 'Eco-friendly hacienda with Mayan-inspired architecture and organic gardens. Pool, spa, and cultural activities.', 'localisation' => '20.6700, -88.5800', 'contact_number' => '+52-999-1234567', 'email' => 'reservations@haciendachichen.com', 'type' => 'boutique', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 42, 'name' => 'Villas Arqueologicas', 'price_per_night' => 85.00, 'description' => 'Budget hotel near Chichen Itza entrance with basic rooms and pool. Simple accommodations for ruins visitors.', 'localisation' => '20.6850, -88.5650', 'contact_number' => '+52-985-1234567', 'email' => 'info@villaschichen.com', 'type' => 'economy', 'image' => 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // BERLIN (City ID: 43) - 52.5200, 13.4050
        $hotels[] = ['city_id' => 43, 'name' => 'Hotel Adlon Kempinski', 'price_per_night' => 520.00, 'description' => 'Iconic luxury hotel next to Brandenburg Gate with historic elegance. Spa, fine dining, and impeccable service.', 'localisation' => '52.5160, 13.3800', 'contact_number' => '+49-30-22610', 'email' => 'reservations.adlon@kempinski.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 43, 'name' => 'TITANIC Gendarmenmarkt Berlin', 'price_per_night' => 180.00, 'description' => 'Modern hotel near Gendarmenmarkt square with spa and pool. Comfortable rooms and central location.', 'localisation' => '52.5130, 13.3920', 'contact_number' => '+49-30-12345678', 'email' => 'info@titanicgendarmenmarkt.de', 'type' => 'mid-range', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 43, 'name' => 'Generator Berlin Mitte', 'price_per_night' => 30.00, 'description' => 'Trendy hostel in central Berlin with bar and rooftop terrace. Dorms, private rooms, and social atmosphere.', 'localisation' => '52.5250, 13.3900', 'contact_number' => '+49-30-12345679', 'email' => 'berlin@generatorhostels.com', 'type' => 'budget', 'image' => 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // MUNICH (City ID: 44) - 48.1351, 11.5820
        $hotels[] = ['city_id' => 44, 'name' => 'Bayerischer Hof', 'price_per_night' => 380.00, 'description' => 'Luxury family-owned hotel with rooftop pool and stunning city views. Spa, multiple restaurants, and central location.', 'localisation' => '48.1400, 11.5780', 'contact_number' => '+49-89-21200', 'email' => 'info@bayerischerhof.de', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 44, 'name' => 'Hotel Königstein', 'price_per_night' => 120.00, 'description' => 'Comfortable mid-range hotel near central station with friendly service. Clean rooms and good breakfast.', 'localisation' => '48.1380, 11.5600', 'contact_number' => '+49-89-1234567', 'email' => 'info@koenigstein-hotel.de', 'type' => 'mid-range', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 44, 'name' => 'Wombat\'s City Hostel', 'price_per_night' => 25.00, 'description' => 'Popular hostel with bar, rooftop terrace, and kitchen facilities. Dorms only, social atmosphere, and cheap rates.', 'localisation' => '48.1350, 11.5820', 'contact_number' => '+49-89-1234568', 'email' => 'munich@wombats-hostels.com', 'type' => 'budget', 'image' => 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // BLACK FOREST (City ID: 45) - 48.2864, 8.2710
        $hotels[] = ['city_id' => 45, 'name' => 'Brenners Park-Hotel & Spa', 'price_per_night' => 420.00, 'description' => 'Legendary luxury hotel in Baden-Baden with stunning spa and park views. Michelin-starred dining and elegant rooms.', 'localisation' => '48.7600, 8.2400', 'contact_number' => '+49-7221-9000', 'email' => 'info@brenners.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 45, 'name' => 'Hotel Traube Tonbach', 'price_per_night' => 280.00, 'description' => 'Family-run hotel in Baiersbronn with three-Michelin-star restaurant. Traditional Black Forest hospitality and spa.', 'localisation' => '48.5200, 8.3800', 'contact_number' => '+49-7442-4920', 'email' => 'info@traube-tonbach.de', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 45, 'name' => 'Gasthof zum Löwen', 'price_per_night' => 85.00, 'description' => 'Traditional guesthouse in Triberg with Black Forest hospitality. Home-cooked meals and cozy atmosphere.', 'localisation' => '48.1300, 8.2300', 'contact_number' => '+49-7722-12345', 'email' => 'info@gasthof-loewen.de', 'type' => 'economy', 'image' => 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // CAPE TOWN (City ID: 46) - -33.9249, 18.4241
        $hotels[] = ['city_id' => 46, 'name' => 'One&Only Cape Town', 'price_per_night' => 550.00, 'description' => 'Luxury waterfront resort with stunning Table Mountain views. Private marina, spa, and Nobu restaurant.', 'localisation' => '-33.9050, 18.4180', 'contact_number' => '+27-21-4315888', 'email' => 'reservations@oneandonlycapetown.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 46, 'name' => 'The Silo Hotel', 'price_per_night' => 650.00, 'description' => 'Iconic hotel in converted grain silo with rooftop pool and art gallery. Stunning views and unique architecture.', 'localisation' => '-33.9060, 18.4210', 'contact_number' => '+27-21-6700500', 'email' => 'stay@thesilo.co.za', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 46, 'name' => 'Once in Cape Town Hostel', 'price_per_night' => 25.00, 'description' => 'Social hostel with rooftop bar and pool in trendy Kloof Street. Dorms, private rooms, and tour desk.', 'localisation' => '-33.9250, 18.4130', 'contact_number' => '+27-21-1234567', 'email' => 'info@onceincapetown.com', 'type' => 'budget', 'image' => 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // KRUGER (City ID: 47) - -24.9598, 31.5921
        $hotels[] = ['city_id' => 47, 'name' => 'Singita Lebombo Lodge', 'price_per_night' => 1200.00, 'description' => 'Ultra-luxury safari lodge with stunning views over the Nwanetsi River. Game drives, spa, and exceptional service.', 'localisation' => '-24.5000, 31.8000', 'contact_number' => '+27-21-6833424', 'email' => 'reservations@singita.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 47, 'name' => 'Lion Sands Game Reserve', 'price_per_night' => 980.00, 'description' => 'Luxury safari lodge with private decks overlooking Sabie River. Treehouse experiences and expert guides.', 'localisation' => '-24.9800, 31.6000', 'contact_number' => '+27-21-1234567', 'email' => 'reservations@lionsands.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 47, 'name' => 'Kruger Park Lodge', 'price_per_night' => 150.00, 'description' => 'Family-friendly resort near Kruger Park with golf course and pools. Self-catering chalets and wildlife viewing.', 'localisation' => '-25.0300, 31.1300', 'contact_number' => '+27-13-1234567', 'email' => 'info@krugerparklodge.co.za', 'type' => 'mid-range', 'image' => 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // JOHANNESBURG (City ID: 48) - -26.2041, 28.0473
        $hotels[] = ['city_id' => 48, 'name' => 'Saxon Hotel', 'price_per_night' => 480.00, 'description' => 'Luxury hotel where Nelson Mandela finished his autobiography. Spa, fine dining, and art collection.', 'localisation' => '-26.1050, 28.0550', 'contact_number' => '+27-11-2926000', 'email' => 'reservations@saxon.co.za', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 48, 'name' => 'The Peech Hotel', 'price_per_night' => 160.00, 'description' => 'Boutique eco-hotel in leafy suburb with pool and garden. Sustainable practices and contemporary design.', 'localisation' => '-26.1280, 28.0550', 'contact_number' => '+27-11-5379797', 'email' => 'stay@thepeech.co.za', 'type' => 'boutique', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 48, 'name' => 'Curiocity Backpackers', 'price_per_night' => 20.00, 'description' => 'Artistic hostel in Maboneng precinct with rooftop bar. Dorms, private rooms, and cultural events.', 'localisation' => '-26.2000, 28.0450', 'contact_number' => '+27-11-1234567', 'email' => 'info@curiocitybackpackers.com', 'type' => 'budget', 'image' => 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // LONDON (City ID: 49) - 51.5074, -0.1278
        $hotels[] = ['city_id' => 49, 'name' => 'The Ritz London', 'price_per_night' => 680.00, 'description' => 'Iconic luxury hotel in Piccadilly with legendary afternoon tea. Michelin-starred dining and impeccable service.', 'localisation' => '51.5070, -0.1410', 'contact_number' => '+44-20-74938181', 'email' => 'reservations@theritzlondon.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 49, 'name' => 'The Hoxton Shoreditch', 'price_per_night' => 180.00, 'description' => 'Trendy boutique hotel in hip Shoreditch with coworking space. Modern rooms, coffee bar, and vibrant atmosphere.', 'localisation' => '51.5260, -0.0800', 'contact_number' => '+44-20-75501000', 'email' => 'shoreditch@thehoxton.com', 'type' => 'boutique', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 49, 'name' => 'Generator London', 'price_per_night' => 35.00, 'description' => 'Design hostel in King\'s Cross with bar, cafe, and outdoor terrace. Dorms and private rooms.', 'localisation' => '51.5300, -0.1240', 'contact_number' => '+44-20-73835555', 'email' => 'london@generatorhostels.com', 'type' => 'budget', 'image' => 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // EDINBURGH (City ID: 50) - 55.9533, -3.1883
        $hotels[] = ['city_id' => 50, 'name' => 'The Balmoral Hotel', 'price_per_night' => 450.00, 'description' => 'Iconic luxury hotel with clock tower overlooking Edinburgh Castle. Spa, Michelin-starred restaurant, and elegant rooms.', 'localisation' => '55.9530, -3.1890', 'contact_number' => '+44-131-5562414', 'email' => 'reservations.balmoral@roccofortehotels.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 50, 'name' => 'The Grassmarket Hotel', 'price_per_night' => 120.00, 'description' => 'Funky boutique hotel in historic Grassmarket with castle views. Vibrant decor and lively atmosphere.', 'localisation' => '55.9490, -3.1950', 'contact_number' => '+44-131-1234567', 'email' => 'stay@grassmarkethotel.com', 'type' => 'mid-range', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 50, 'name' => 'Castle Rock Hostel', 'price_per_night' => 30.00, 'description' => 'Popular hostel near Edinburgh Castle with free breakfast. Dorms, social events, and central location.', 'localisation' => '55.9480, -3.2000', 'contact_number' => '+44-131-1234568', 'email' => 'info@castlerockhostel.com', 'type' => 'budget', 'image' => 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // LAKE DISTRICT (City ID: 51) - 54.4609, -3.0886
        $hotels[] = ['city_id' => 51, 'name' => 'Gilpin Hotel & Lake House', 'price_per_night' => 380.00, 'description' => 'Luxury hotel with private hot tubs and spa treatments. Michelin-starred dining and beautiful grounds.', 'localisation' => '54.3100, -2.9100', 'contact_number' => '+44-1539-888818', 'email' => 'enquiries@gilpinhotel.co.uk', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 51, 'name' => 'The Samling Hotel', 'price_per_night' => 320.00, 'description' => 'Boutique hotel with stunning Windermere lake views. Fine dining, spa, and romantic atmosphere.', 'localisation' => '54.3700, -2.9100', 'contact_number' => '+44-1539-123456', 'email' => 'info@thesamling.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 51, 'name' => 'YHA Ambleside', 'price_per_night' => 35.00, 'description' => 'Budget hostel on Lake Windermere with self-catering facilities. Dorms, private rooms, and stunning views.', 'localisation' => '54.4300, -2.9700', 'contact_number' => '+44-845-1234567', 'email' => 'ambleside@yha.org.uk', 'type' => 'budget', 'image' => 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // ISTANBUL (City ID: 52) - 41.0082, 28.9784
        $hotels[] = ['city_id' => 52, 'name' => 'Four Seasons Istanbul at Sultanahmet', 'price_per_night' => 520.00, 'description' => 'Luxury hotel in former prison with stunning Blue Mosque views. Rooftop terrace, spa, and impeccable service.', 'localisation' => '41.0050, 28.9760', 'contact_number' => '+90-212-4023000', 'email' => 'reservations.istanbul@fourseasons.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 52, 'name' => 'Sultanhan Hotel', 'price_per_night' => 110.00, 'description' => 'Traditional Turkish hotel near Hagia Sophia with rooftop terrace. Comfortable rooms and friendly service.', 'localisation' => '41.0080, 28.9780', 'contact_number' => '+90-212-1234567', 'email' => 'info@sultanhanhotel.com', 'type' => 'mid-range', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 52, 'name' => 'Cheers Hostel', 'price_per_night' => 20.00, 'description' => 'Popular backpacker hostel in Sultanahmet with rooftop terrace. Dorms, free breakfast, and social events.', 'localisation' => '41.0090, 28.9770', 'contact_number' => '+90-212-1234568', 'email' => 'info@cheershostel.com', 'type' => 'budget', 'image' => 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // CAPPADOCIA (City ID: 53) - 38.6430, 34.8294
        $hotels[] = ['city_id' => 53, 'name' => 'Museum Hotel', 'price_per_night' => 420.00, 'description' => 'Unique cave hotel with antique furnishings and stunning valley views. Infinity pool, spa, and hot air balloon tours.', 'localisation' => '38.6400, 34.8300', 'contact_number' => '+90-384-1234567', 'email' => 'reservations@museumhotel.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 53, 'name' => 'Sultan Cave Suites', 'price_per_night' => 180.00, 'description' => 'Famous cave hotel with iconic terrace overlooking balloons. Traditional decor and warm hospitality.', 'localisation' => '38.6410, 34.8280', 'contact_number' => '+90-384-1234568', 'email' => 'info@sultancavesuites.com', 'type' => 'mid-range', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 53, 'name' => 'Kelebek Hotel', 'price_per_night' => 90.00, 'description' => 'Cozy cave hotel with traditional Turkish decor and garden. Affordable rates and friendly atmosphere.', 'localisation' => '38.6420, 34.8290', 'contact_number' => '+90-384-1234569', 'email' => 'info@kelebekhotel.com', 'type' => 'economy', 'image' => 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // PAMUKKALE (City ID: 54) - 37.9225, 29.1226
        $hotels[] = ['city_id' => 54, 'name' => 'Doga Thermal Health & Spa', 'price_per_night' => 150.00, 'description' => 'Thermal hotel with natural hot springs and spa treatments. Modern rooms and healing waters.', 'localisation' => '37.9200, 29.1200', 'contact_number' => '+90-258-1234567', 'email' => 'info@dogathermal.com', 'type' => 'mid-range', 'image' => 'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 54, 'name' => 'Venus Suite Hotel', 'price_per_night' => 80.00, 'description' => 'Family-run hotel with pool and terrace near travertines. Simple rooms and home-cooked meals.', 'localisation' => '37.9210, 29.1230', 'contact_number' => '+90-258-1234568', 'email' => 'info@venussuite.com', 'type' => 'economy', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 54, 'name' => 'Melrose House Hotel', 'price_per_night' => 65.00, 'description' => 'Boutique pension with garden and pool near Pamukkale entrance. Cozy rooms and friendly service.', 'localisation' => '37.9220, 29.1240', 'contact_number' => '+90-258-1234569', 'email' => 'info@melrosehouse.com', 'type' => 'budget', 'image' => 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // BALI (City ID: 55) - -8.3405, 115.0920
        $hotels[] = ['city_id' => 55, 'name' => 'Four Seasons Resort Bali at Sayan', 'price_per_night' => 580.00, 'description' => 'Luxury resort in Ubud with stunning Ayung River views. Infinity pool, spa, and cultural experiences.', 'localisation' => '-8.5000, 115.2500', 'contact_number' => '+62-361-1234567', 'email' => 'reservations.bali@fourseasons.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 55, 'name' => 'The Kayon Jungle Resort', 'price_per_night' => 320.00, 'description' => 'Boutique resort with infinity pool overlooking jungle. Spa, fine dining, and romantic atmosphere.', 'localisation' => '-8.4950, 115.2600', 'contact_number' => '+62-361-1234568', 'email' => 'info@thekayonjungle.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 55, 'name' => 'Puri Garden Hotel & Hostel', 'price_per_night' => 25.00, 'description' => 'Social hostel with pool, yoga, and free breakfast in Seminyak. Dorms, private rooms, and events.', 'localisation' => '-8.6800, 115.1600', 'contact_number' => '+62-361-1234569', 'email' => 'info@purigardenbali.com', 'type' => 'budget', 'image' => 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // JAKARTA (City ID: 56) - -6.2088, 106.8456
        $hotels[] = ['city_id' => 56, 'name' => 'Ritz-Carlton Jakarta', 'price_per_night' => 280.00, 'description' => 'Luxury hotel in Mega Kuningan with spa and fine dining. Elegant rooms and impeccable service.', 'localisation' => '-6.2250, 106.8300', 'contact_number' => '+62-21-1234567', 'email' => 'reservations.jakarta@ritzcarlton.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 56, 'name' => 'Ashley Hotel', 'price_per_night' => 65.00, 'description' => 'Modern budget hotel in central Jakarta with clean rooms. Free breakfast and good location.', 'localisation' => '-6.2000, 106.8500', 'contact_number' => '+62-21-1234568', 'email' => 'info@ashleyhotel.com', 'type' => 'economy', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 56, 'name' => 'Six Degrees Hostel', 'price_per_night' => 15.00, 'description' => 'Social hostel with bar and rooftop in South Jakarta. Dorms, events, and friendly atmosphere.', 'localisation' => '-6.2400, 106.8000', 'contact_number' => '+62-21-1234569', 'email' => 'hello@sixdegreeshostel.com', 'type' => 'budget', 'image' => 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // YOGYAKARTA (City ID: 57) - -7.7956, 110.3695
        $hotels[] = ['city_id' => 57, 'name' => 'The Phoenix Hotel Yogyakarta', 'price_per_night' => 120.00, 'description' => 'Historic luxury hotel with colonial architecture and gardens. Pool, spa, and traditional Javanese hospitality.', 'localisation' => '-7.7820, 110.3660', 'contact_number' => '+62-274-1234567', 'email' => 'reservations@thephoenixhotel.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 57, 'name' => 'Greenhost Boutique Hotel', 'price_per_night' => 55.00, 'description' => 'Eco-friendly boutique hotel with modern design and garden. Rooftop bar and sustainable practices.', 'localisation' => '-7.8000, 110.3750', 'contact_number' => '+62-274-1234568', 'email' => 'info@greenhosthotel.com', 'type' => 'boutique', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 57, 'name' => 'Gria Indah Hostel', 'price_per_night' => 12.00, 'description' => 'Budget hostel near Malioboro with simple rooms. Basic amenities and friendly staff.', 'localisation' => '-7.7950, 110.3700', 'contact_number' => '+62-274-1234569', 'email' => 'info@griaindah.com', 'type' => 'budget', 'image' => 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // LISBON (City ID: 58) - 38.7223, -9.1393
        $hotels[] = ['city_id' => 58, 'name' => 'Olissippo Lapa Palace', 'price_per_night' => 350.00, 'description' => 'Luxury palace hotel overlooking Tagus River with lush gardens. Pool, spa, and elegant rooms.', 'localisation' => '38.7100, -9.1600', 'contact_number' => '+351-21-1234567', 'email' => 'reservations@lappalace.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 58, 'name' => 'Memmo Alfama Hotel', 'price_per_night' => 180.00, 'description' => 'Boutique hotel in historic Alfama with rooftop pool and city views. Modern design and central location.', 'localisation' => '38.7120, -9.1300', 'contact_number' => '+351-21-1234568', 'email' => 'info@memmoalfama.com', 'type' => 'boutique', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 58, 'name' => 'Home Lisbon Hostel', 'price_per_night' => 25.00, 'description' => 'Award-winning hostel with home-cooked dinners and social atmosphere. Dorms, private rooms, and central location.', 'localisation' => '38.7150, -9.1400', 'contact_number' => '+351-21-1234569', 'email' => 'hello@homelisbonhostel.com', 'type' => 'budget', 'image' => 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // ALGARVE (City ID: 59) - 37.0194, -7.9304
        $hotels[] = ['city_id' => 59, 'name' => 'Vilalara Thalassa Resort', 'price_per_night' => 320.00, 'description' => 'Luxury beach resort with thalassotherapy spa and cliffside pools. Fine dining and stunning ocean views.', 'localisation' => '37.0900, -8.3300', 'contact_number' => '+351-289-1234567', 'email' => 'reservations@vilalara.com', 'type' => 'resort', 'image' => 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 59, 'name' => 'Cascade Wellness Resort', 'price_per_night' => 210.00, 'description' => 'Family-friendly resort with pools, spa, and golf course. Modern rooms and ocean views.', 'localisation' => '37.0860, -8.6700', 'contact_number' => '+351-282-1234567', 'email' => 'info@cascadealgarve.com', 'type' => 'resort', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 59, 'name' => 'Algarve Hostel', 'price_per_night' => 20.00, 'description' => 'Budget hostel in Lagos with pool and bar. Dorms, private rooms, and social events.', 'localisation' => '37.1000, -8.6700', 'contact_number' => '+351-282-1234568', 'email' => 'info@algarvehostel.com', 'type' => 'budget', 'image' => 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // PORTO (City ID: 60) - 41.1579, -8.6291
        $hotels[] = ['city_id' => 60, 'name' => 'The Yeatman Hotel', 'price_per_night' => 350.00, 'description' => 'Luxury wine hotel with stunning Douro River and Porto views. Spa, Michelin-starred restaurant, and wine cellar.', 'localisation' => '41.1350, -8.6150', 'contact_number' => '+351-22-1331000', 'email' => 'reservations@theyeatman.com', 'type' => 'luxury', 'image' => 'https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 60, 'name' => 'Pestana Vintage Porto', 'price_per_night' => 180.00, 'description' => 'Historic hotel on Ribeira Square with river views. Classic decor and central location.', 'localisation' => '41.1400, -8.6150', 'contact_number' => '+351-22-1234567', 'email' => 'info@pestana.com', 'type' => 'mid-range', 'image' => 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg', 'created_at' => now(), 'updated_at' => now()];
        $hotels[] = ['city_id' => 60, 'name' => 'Gallery Hostel Porto', 'price_per_night' => 30.00, 'description' => 'Art-focused hostel with gallery and garden in historic building. Dorms, private rooms, and creative atmosphere.', 'localisation' => '41.1480, -8.6100', 'contact_number' => '+351-22-1234568', 'email' => 'hello@gallery-hostel.com', 'type' => 'budget', 'image' => 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg', 'created_at' => now(), 'updated_at' => now()];

        // Insert all hotels
        DB::table('hotels')->insert($hotels);
    }
}